algoritmo "media"



var

      prova1, prova2, prova3, trab : inteiro
      media : real


inicio

     escreva("Digite a nota da prova 1: ")
     leia(prova1)
     escreva("Digite a nota da prova 2: ")
     leia(prova2)
     escreva("Digite a nota da prova 3: ")
     leia(prova3)
     escreva("Digite a nota do trabalho: ")
     leia(trab)
     
     media <- (prova1 + prova2 + prova3 + trab) / 4
     
     escreval("A media do Aluno é: ", media:8:2)


fimalgoritmo
