algoritmo "crescente_enquanto"


var

   x, y : inteiro

inicio

   escreval("Digite dois numeros: ")
   leia(x)
   leia(y)
   
   enquanto x <> y faca
   
            se x < y entao
               escreval("CRESCENTE")
            senao
                 escreval("DECRESCENTE")
            fimse
            
   escreval("Digite outros dois numeros: ")
   leia(x)
   leia(y)
   
   fimenquanto

   
   


fimalgoritmo
